-- Migration: create initial schema for FannyBet application
-- Tables
CREATE TABLE IF NOT EXISTS matchdays (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  super_jackpot NUMERIC,
  deadline TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id),
  matchday_id BIGINT REFERENCES matchdays(id),
  team TEXT,
  amount NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS survival_seasons (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  prize_pool NUMERIC,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS survival_players (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id),
  season_id BIGINT REFERENCES survival_seasons(id),
  eliminated BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS survival_picks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  player_id BIGINT REFERENCES survival_players(id),
  matchday_id BIGINT REFERENCES matchdays(id),
  team TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_bets_user_id ON bets(user_id);
CREATE INDEX IF NOT EXISTS idx_bets_matchday_id ON bets(matchday_id);
CREATE INDEX IF NOT EXISTS idx_survival_players_user_id ON survival_players(user_id);
CREATE INDEX IF NOT EXISTS idx_survival_picks_player_id ON survival_picks(player_id);
