-- Migration: Create FB Lega (Championship Mode) Schema
-- Description: Adds tables for leagues, participants, and league-specific picks.

-- 1. Create fb_leagues Table
CREATE TABLE IF NOT EXISTS public.fb_leagues (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    admin_id UUID REFERENCES public.profiles(id),
    entry_fee INTEGER DEFAULT 0,
    duration_matchdays INTEGER DEFAULT 5,
    current_round INTEGER DEFAULT 0,
    start_matchday_id BIGINT REFERENCES public.matchdays(id),
    scoring_rules JSONB NOT NULL DEFAULT '{"1": 1, "X": 1, "2": 1}',
    prize_distribution JSONB NOT NULL DEFAULT '[1.0]', -- [1.0] = 100% to 1st, [0.7, 0.3] = 70% to 1st, 30% to 2nd
    status TEXT DEFAULT 'OPEN', -- OPEN (joining), ACTIVE (ongoing), COMPLETED
    prize_pool NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. Create fb_league_participants Table
CREATE TABLE IF NOT EXISTS public.fb_league_participants (
    league_id BIGINT REFERENCES public.fb_leagues(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    total_points INTEGER DEFAULT 0,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (league_id, user_id)
);

-- 3. Create fb_league_picks Table
CREATE TABLE IF NOT EXISTS public.fb_league_picks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    league_id BIGINT REFERENCES public.fb_leagues(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    matchday_id BIGINT REFERENCES public.matchdays(id),
    predictions TEXT[] NOT NULL,
    points_earned INTEGER DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE (league_id, user_id, matchday_id)
);

-- 4. Enable RLS
ALTER TABLE public.fb_leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fb_league_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fb_league_picks ENABLE ROW LEVEL SECURITY;

-- 5. Policies
-- fb_leagues: everyone can view, only admin can manage (already covered by is_admin helper in previous migrations)
CREATE POLICY "Public can view leagues" ON public.fb_leagues FOR SELECT USING (true);
CREATE POLICY "Admins can manage leagues" ON public.fb_leagues FOR ALL USING (public.is_admin());

-- fb_league_participants: everyone can view, users can join themselves
CREATE POLICY "Public can view participants" ON public.fb_league_participants FOR SELECT USING (true);
CREATE POLICY "Users can join leagues" ON public.fb_league_participants FOR INSERT WITH CHECK (auth.uid() = user_id);

-- fb_league_picks: users can view their own and others (once closed?), but only insert their own
CREATE POLICY "Users can view league picks" ON public.fb_league_picks FOR SELECT USING (true);
CREATE POLICY "Users can submit league picks" ON public.fb_league_picks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own picks" ON public.fb_league_picks FOR UPDATE USING (auth.uid() = user_id);

-- 6. Indexes
CREATE INDEX IF NOT EXISTS idx_fb_league_picks_league_id ON fb_league_picks(league_id);
CREATE INDEX IF NOT EXISTS idx_fb_league_picks_user_id ON fb_league_picks(user_id);
CREATE INDEX IF NOT EXISTS idx_fb_league_participants_user_id ON fb_league_participants(user_id);
