-- CONSOLIDATED FIX: FB LEAGUE ARCHIVE & UNDERDOG CARD
-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. Correct Underdog Card Registration
INSERT INTO public.collectible_cards (title, description, rarity, category, image_url)
VALUES (
    'UNDERDOG',
    'Sbloccata indovinando il risultato meno pronosticato in FB Lega (Bonus Underdog).',
    'RARE',
    'ACHIEVEMENT',
    'https://rzyscsvzentuplsgoipv.supabase.co/storage/v1/object/public/cards/Underdog.png'
)
ON CONFLICT (title) DO UPDATE SET 
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url;

-- 2. Create Matchday Results Table
CREATE TABLE IF NOT EXISTS public.fb_league_matchday_results (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    league_id BIGINT REFERENCES public.fb_leagues(id) ON DELETE CASCADE,
    matchday_id BIGINT REFERENCES public.matchdays(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    points_matchday INTEGER NOT NULL,
    points_total INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    active_bonuses JSONB DEFAULT '[]'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE (league_id, matchday_id, user_id)
);

ALTER TABLE public.fb_league_matchday_results ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view historical results" ON public.fb_league_matchday_results;
CREATE POLICY "Public can view historical results" ON public.fb_league_matchday_results FOR SELECT USING (true);

-- 3. Update resolve_fb_league_round RPC
CREATE OR REPLACE FUNCTION public.resolve_fb_league_round(p_league_id BIGINT, p_matchday_id BIGINT)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_results TEXT[]; 
    v_jolly_idx INTEGER; 
    v_rules JSONB; 
    v_total_picks INTEGER; 
    v_match_counts JSONB := '{}'::JSONB;
    v_card_hattrick_id UUID; 
    v_card_underdog_id UUID; 
    v_resolved_count INTEGER := 0; 
    v_rec RECORD;
BEGIN
    IF NOT public.is_admin() THEN 
        RETURN json_build_object('success', false, 'message', 'Unauthorized'); 
    END IF;

    SELECT scoring_rules INTO v_rules FROM public.fb_leagues WHERE id = p_league_id;
    SELECT results, jolly_match_index INTO v_results, v_jolly_idx FROM public.matchdays WHERE id = p_matchday_id AND status = 'CLOSED';
    
    IF v_results IS NULL THEN 
        RETURN json_build_object('success', false, 'message', 'Matchday results not found'); 
    END IF;

    SELECT id INTO v_card_hattrick_id FROM public.collectible_cards WHERE title = 'Hat-trick';
    SELECT id INTO v_card_underdog_id FROM public.collectible_cards WHERE title = 'UNDERDOG';

    IF (v_rules->>'underdog_enabled')::BOOLEAN THEN
        SELECT COUNT(*)::INTEGER INTO v_total_picks FROM public.fb_league_picks WHERE league_id = p_league_id AND matchday_id = p_matchday_id;
        IF v_total_picks > 0 THEN
            SELECT jsonb_object_agg(m_idx, counts) INTO v_match_counts 
            FROM (
                SELECT i::TEXT as m_idx, jsonb_object_agg(pred, cnt) as counts 
                FROM (
                    SELECT s.i, lp.predictions[s.i] as pred, COUNT(*)::INTEGER as cnt 
                    FROM public.fb_league_picks lp CROSS JOIN generate_series(1, 10) AS s(i) 
                    WHERE lp.league_id = p_league_id AND lp.matchday_id = p_matchday_id AND lp.predictions[s.i] IS NOT NULL 
                    GROUP BY s.i, lp.predictions[s.i]
                ) inner_s GROUP BY i
            ) t;
        END IF;
    END IF;

    CREATE TEMP TABLE round_calculation ON COMMIT DROP AS
    WITH raw_picks AS (
        SELECT lp.user_id, pk.id as pick_id, pk.predictions, lp.total_points as accumulated_points 
        FROM public.fb_league_participants lp 
        JOIN public.fb_league_picks pk ON pk.league_id = lp.league_id AND pk.user_id = lp.user_id AND pk.matchday_id = p_matchday_id 
        WHERE lp.league_id = p_league_id AND pk.points_earned IS NULL
    ),
    calculated AS (
        SELECT 
            rp.user_id, 
            rp.pick_id, 
            rp.accumulated_points, 
            (
                SELECT COALESCE(SUM(
                    CASE 
                        WHEN rp.predictions[s.i] = v_results[s.i] THEN 
                            COALESCE((v_rules->>v_results[s.i])::INTEGER, 1) + 
                            (CASE WHEN v_jolly_idx IS NOT NULL AND (s.i - 1) = v_jolly_idx THEN 2 ELSE 0 END) + 
                            (CASE 
                                WHEN (v_rules->>'underdog_enabled')::BOOLEAN AND v_total_picks > 3 AND rp.predictions[s.i] IS NOT NULL 
                                  AND ((v_match_counts->s.i::TEXT->>rp.predictions[s.i])::INTEGER::FLOAT / v_total_picks::FLOAT) < 0.15 
                                THEN 2 ELSE 0 
                             END) 
                        ELSE 0 
                    END
                ), 0)::INTEGER FROM generate_series(1, 10) AS s(i)
            ) as round_match_points, 
            (SELECT COUNT(*) FROM generate_series(1,10) s(i) WHERE rp.predictions[s.i] = v_results[s.i])::INTEGER as correct_count, 
            (
                SELECT COALESCE(MAX(consecutive), 0) FROM (
                    SELECT COUNT(*) OVER (PARTITION BY grp) as consecutive 
                    FROM (
                        SELECT s.i, s.i - ROW_NUMBER() OVER (ORDER BY s.i) as grp 
                        FROM generate_series(1, 10) s(i) 
                        WHERE rp.predictions[s.i] = v_results[s.i]
                    ) groups
                ) final_consecutive
            )::INTEGER as max_consecutive 
        FROM raw_picks rp
    ),
    final_scores AS (
        SELECT 
            c.*, 
            (c.round_match_points + (CASE WHEN c.max_consecutive >= 3 THEN 3 ELSE 0 END) + (CASE WHEN c.correct_count = 10 THEN 10 ELSE 0 END))::INTEGER as round_total_points 
        FROM calculated c
    ),
    ranked_results AS (
        SELECT 
            fs.*, 
            RANK() OVER (ORDER BY (fs.accumulated_points + fs.round_total_points) DESC) as final_rank, 
            (
                SELECT jsonb_agg(bonus) FROM (
                    SELECT 'jolly' as bonus WHERE v_jolly_idx IS NOT NULL AND (SELECT rp.predictions[v_jolly_idx + 1] FROM raw_picks rp WHERE rp.user_id = fs.user_id) = v_results[v_jolly_idx + 1] 
                    UNION ALL SELECT 'strike' WHERE fs.max_consecutive >= 3 
                    UNION ALL SELECT 'en_plein' WHERE fs.correct_count = 10 
                    UNION ALL SELECT 'underdog' WHERE EXISTS (
                        SELECT 1 FROM generate_series(1, 10) AS s(i) 
                        JOIN raw_picks rp2 ON rp2.user_id = fs.user_id 
                        WHERE rp2.predictions[s.i] = v_results[s.i] 
                        AND (v_rules->>'underdog_enabled')::BOOLEAN 
                        AND v_total_picks > 3 
                        AND ((v_match_counts->s.i::TEXT->>rp2.predictions[s.i])::INTEGER::FLOAT / v_total_picks::FLOAT) < 0.15
                    )
                ) b
            ) as bonuses 
        FROM final_scores fs
    )
    SELECT * FROM ranked_results;

    FOR v_rec IN SELECT * FROM round_calculation LOOP
        UPDATE public.fb_league_picks SET points_earned = v_rec.round_total_points WHERE id = v_rec.pick_id;
        UPDATE public.fb_league_participants SET total_points = total_points + v_rec.round_total_points WHERE league_id = p_league_id AND user_id = v_rec.user_id;
        INSERT INTO public.fb_league_matchday_results (league_id, matchday_id, user_id, points_matchday, points_total, rank, active_bonuses) 
        VALUES (p_league_id, p_matchday_id, v_rec.user_id, v_rec.round_total_points, v_rec.accumulated_points + v_rec.round_total_points, v_rec.final_rank, COALESCE(v_rec.bonuses, '[]'::JSONB));
        
        IF v_card_hattrick_id IS NOT NULL AND v_rec.max_consecutive >= 3 THEN 
            INSERT INTO public.user_cards (user_id, card_id) VALUES (v_rec.user_id, v_card_hattrick_id) ON CONFLICT DO NOTHING; 
        END IF;
        IF v_card_underdog_id IS NOT NULL AND EXISTS (SELECT 1 FROM jsonb_array_elements_text(v_rec.bonuses) WHERE value = 'underdog') THEN 
            INSERT INTO public.user_cards (user_id, card_id) VALUES (v_rec.user_id, v_card_underdog_id) ON CONFLICT DO NOTHING; 
        END IF;
        
        v_resolved_count := v_resolved_count + 1;
    END LOOP;

    UPDATE public.fb_leagues SET current_round = current_round + 1 WHERE id = p_league_id;
    RETURN json_build_object('success', true, 'message', 'Round risolto e archiviato', 'resolved_count', v_resolved_count);
END;
$$;

-- 4. Historical Leaderboard RPC
CREATE OR REPLACE FUNCTION public.get_fb_league_historical_leaderboard(p_league_id BIGINT, p_matchday_id BIGINT)
RETURNS TABLE (user_id UUID, username TEXT, points_matchday INTEGER, points_total INTEGER, rank INTEGER, active_bonuses JSONB) 
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY 
    SELECT 
        mr.user_id, 
        p.username, 
        mr.points_matchday, 
        mr.points_total, 
        mr.rank, 
        mr.active_bonuses 
    FROM public.fb_league_matchday_results mr 
    JOIN public.profiles p ON p.id = mr.user_id 
    WHERE mr.league_id = p_league_id AND mr.matchday_id = p_matchday_id 
    ORDER BY mr.rank ASC, p.username ASC;
END;
$$;

-- 5. Backfill Historical Data
DO $$
DECLARE
    v_league_id BIGINT;
    v_rules JSONB;
    v_md_rec RECORD;
BEGIN
    FOR v_league_id, v_rules IN SELECT id, scoring_rules FROM public.fb_leagues LOOP
        FOR v_md_rec IN 
            SELECT md.id as matchday_id, md.results, md.jolly_match_index, m.round_number 
            FROM public.get_fb_league_matchdays(v_league_id) m 
            JOIN public.matchdays md ON md.id = m.matchday_id 
            WHERE md.status IN ('CLOSED', 'ARCHIVED') 
              AND md.results IS NOT NULL 
              AND NOT EXISTS (SELECT 1 FROM public.fb_league_matchday_results mr WHERE mr.league_id = v_league_id AND mr.matchday_id = md.id) 
            ORDER BY m.round_number ASC
        LOOP
            -- Simplified Backfill: calculate and insert into a temp table per matchday
            CREATE TEMP TABLE temp_backfill_scores ON COMMIT DROP AS
            WITH user_stats AS (
                SELECT 
                    lp.user_id,
                    (
                        SELECT COALESCE(SUM(CASE WHEN pk.predictions[s.i] = v_md_rec.results[s.i] THEN COALESCE((v_rules->>v_md_rec.results[s.i])::INTEGER, 1) + (CASE WHEN v_md_rec.jolly_match_index IS NOT NULL AND (s.i - 1) = v_md_rec.jolly_match_index THEN 2 ELSE 0 END) ELSE 0 END), 0)::INTEGER
                        FROM public.fb_league_picks pk, generate_series(1, 10) s(i)
                        WHERE pk.league_id = v_league_id AND pk.matchday_id = v_md_rec.matchday_id AND pk.user_id = lp.user_id
                    ) as round_match_pts,
                    (
                        SELECT COALESCE(SUM(pk_p.points_earned), 0)
                        FROM public.fb_league_picks pk_p
                        JOIN public.get_fb_league_matchdays(v_league_id) gmd ON gmd.matchday_id = pk_p.matchday_id
                        WHERE pk_p.league_id = v_league_id AND pk_p.user_id = lp.user_id AND gmd.round_number <= v_md_rec.round_number
                    ) as total_then
                FROM public.fb_league_participants lp
                WHERE lp.league_id = v_league_id
            )
            SELECT *, RANK() OVER (ORDER BY total_then DESC) as pos FROM user_stats;

            INSERT INTO public.fb_league_matchday_results (league_id, matchday_id, user_id, points_matchday, points_total, rank)
            SELECT v_league_id, v_md_rec.matchday_id, user_id, round_match_pts, total_then, pos FROM temp_backfill_scores;
            
            DROP TABLE temp_backfill_scores;
        END LOOP;
    END LOOP;
END;
$$;
